In [1]:
import pandas as pd 
import numpy as np

In [2]:
data = pd.read_csv("train.csv")

In [3]:
data = data.drop(['music','hq','fullscreen'], axis=1)

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26296946 entries, 0 to 26296945
Data columns (total 17 columns):
 #   Column          Dtype
---  ------          -----
 0   session_id      int64
 1   index           int64
 2   elapsed_time    int64
 3   event_name      object
 4   name            object
 5   level           int64
 6   page            float64
 7   room_coor_x     float64
 8   room_coor_y     float64
 9   screen_coor_x   float64
 10  screen_coor_y   float64
 11  hover_duration  float64
 12  text            object
 13  fqid            object
 14  room_fqid       object
 15  text_fqid       object
 16  level_group     object
dtypes: float64(6), int64(4), object(7)
memory usage: 3.3+ GB

In [5]:
data

,session_id,index,elapsed_time,event_name,name,level,page,room_coor_x,room_coor_y,screen_coor_x,screen_coor_y,hover_duration,text,fqid,room_fqid,text_fqid,level_group
0,20090312431273200,0,0,cutscene_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,undefined,intro,tunic.historicalsociety.closet,tunic.historicalsociety.closet.intro,0-4
1,20090312431273200,1,1323,person_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,"Whatcha doing over there, Jo?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4
2,20090312431273200,2,831,person_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,Just talking to Teddy.,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4
3,20090312431273200,3,1147,person_click,basic,0,NaN,-413.991405,-159.314686,380.0,494.0,NaN,I gotta run to my meeting!,gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4
4,20090312431273200,4,1863,person_click,basic,0,NaN,-412.991405,-159.314686,381.0,494.0,NaN,"Can I come, Gramps?",gramps,tunic.historicalsociety.closet,tunic.historicalsociety.closet.gramps.intro_0_...,0-4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26296941,22100221145014656,1600,5483231,navigate_click,undefined,22,NaN,343.887291,36.701026,483.0,273.0,NaN,NaN,NaN,tunic.capitol_2.hall,NaN,13-22
26296942,22100221145014656,1601,5485166,navigate_click,undefined,22,NaN,332.696070,141.493178,545.0,221.0,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,13-22
26296943,22100221145014656,1602,5485917,navigate_click,undefined,22,NaN,369.912859,140.569205,611.0,217.0,NaN,NaN,NaN,tunic.capitol_2.hall,NaN,13-22
26296944,22100221145014656,1603,5486753,navigate_click,undefined,22,NaN,252.299653,123.805889,526.0,232.0,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,13-22
26296945,22100221145014656,1604,5487952,checkpoint,basic,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,chap4_finale_c,tunic.capitol_2.hall,NaN,13-22

In [8]:
test = data

In [9]:
test['session_id'][:50]

0     20090312431273200
1     20090312431273200
2     20090312431273200
3     20090312431273200
4     20090312431273200
5     20090312431273200
6     20090312431273200
7     20090312431273200
8     20090312431273200
9     20090312431273200
10    20090312431273200
11    20090312431273200
12    20090312431273200
13    20090312431273200
14    20090312431273200
15    20090312431273200
16    20090312431273200
17    20090312431273200
18    20090312431273200
19    20090312431273200
20    20090312431273200
21    20090312431273200
22    20090312431273200
23    20090312431273200
24    20090312431273200
25    20090312431273200
26    20090312431273200
27    20090312431273200
28    20090312431273200
29    20090312431273200
30    20090312431273200
31    20090312431273200
32    20090312431273200
33    20090312431273200
34    20090312431273200
35    20090312431273200
36    20090312431273200
37    20090312431273200
38    20090312431273200
39    20090312431273200
40    20090312431273200
41    20090312431273200
42    20090312431273200
43    20090312431273200
44    20090312431273200
45    20090312431273200
46    20090312431273200
47    20090312431273200
48    20090312431273200
49    20090312431273200
Name: session_id, dtype: int64